service:
  name: laconia-examples-serverless-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'eu-west-1'}

functions:
  greet:
    handler: src/handler.greet
